### ISSUE TITLE
Discussion of inner distance in paired end to ciri2 result

### ISSUE THREAD

**Issue by gumingmu** [bioinfo-biols/CIRI-cookbook#5]
I know CIRI2 will filter reads by PEM signals. But i am confused about if the inner distance of  ciricular RNA reads is low, will CIRI2 filter this reads by PEM signals.

**Comment by Kevinzjy** [comment]
Hi @gumingmu, are you talking about situations where the fragment size is relatively small so distance between read1 and read2 is very small?

As you mentioned, CIRI2 only use PEM signals to filter false positives, which means that if a back-splicing event is detected in read1, read2 must align inside the back-splicing junction. Otherwise, the read pair will be discarded. So as long as the read1 and read2 have correct alignment pattern, their distance won't affect the PEM filter step.
